#########################
## Config for sass-lint.
##
## This should be kept in sync with .sass-lint-auto-fix.yml.
#########################
# Linter Options
options:
  # Don't merge default rules
  merge-default-rules: false
  # Set the formatter to 'stylish'
  formatter: stylish
  # Raise an error if more than 50 warnings are generated
  max-warnings: 50
# File Options
files:
  include: 'scss/**/*.s+(a|c)ss'
# Rule Configuration
rules:
  extends-before-mixins: 2
  extends-before-declarations: 2
  placeholder-in-extend: 0
  mixins-before-declarations:
    - 2
    -
      exclude:
        - breakpoint
        - mq

  no-warn: 1
  no-debug: 1
  no-ids: 0 # Sadly, this just doesn't work when styling Drupal...
  no-important: 1
  hex-notation:
    - 1
    -
      style: uppercase
  indentation:
    - 2
    -
      size: 2
