<?php

/**
 * @file
 * Views Custom Map module.
 */

/**
 * Implements hook_views_api().
 */
function views_custom_map_views_api() {
  return array(
    'api' => 2,
  );
}

/**
 * Implements hook_theme().
 */
function views_custom_map_theme() {
  return array(
    'views_custom_map' => array(
      'variables' => array('points' => NULL, 'map' => NULL),
      'file' => 'views_custom_map.theme.inc',
    ),
    'views_custom_map_point' => array(
      'variables' => array('point' => NULL),
      'file' => 'views_custom_map.theme.inc',
    ),
    'views_custom_map_popup' => array(
      'variables' => array('point' => NULL),
      'file' => 'views_custom_map.theme.inc',
    ),
  );
}
